[PHP]
engine=On
short_open_tag=Off
precision=14
output_buffering=4096
serialize_precision=-1
expose_php=Off
max_execution_time=30
max_input_time=60
memory_limit=256M
error_reporting=E_ALL
display_errors=Off
display_startup_errors=Off
log_errors=On
;variables_order="EGPCS"
variables_order="GPCS"
request_order="GP"
post_max_size=16M
upload_max_filesize=16M
default_charset="UTF-8"
extension_dir="${FRANKENPHP_EXT_DIR}"


; ============================================================
; CORE / LARAVEL
; ============================================================
extension=bcmath
extension=curl
extension=fileinfo
extension=intl
extension=mbstring
extension=openssl
extension=sodium
extension=xml
extension=zip

; ============================================================
; PERFORMANCE / OCTANE
; ============================================================
extension=opcache
extension=pcntl


; ============================================================
; REDIS / CACHE / QUEUES / HORIZON
; ============================================================
extension=redis


; ============================================================
; IMAGE PROCESSING
; ============================================================
extension=gd
;extension=imagick
extension=exif


; ============================================================
; DATABASE CORE
; ============================================================
extension=pdo


; ============================================================
; MYSQL / MARIADB
; ============================================================
extension=mysqli
extension=pdo_mysql


; ============================================================
; POSTGRESQL
; ============================================================
extension=pgsql
extension=pdo_pgsql


; ============================================================
; SQLITE
; ============================================================
extension=sqlite3
extension=pdo_sqlite


; ============================================================
; MICROSOFT SQL SERVER
; ============================================================
extension=sqlsrv
extension=pdo_sqlsrv


; ============================================================
; NETWORKING
; ============================================================
extension=sockets
extension=ftp


; ============================================================
; SOAP / XML
; ============================================================
extension=soap
extension=xsl

[Date]
date.timezone=UTC

[Session]
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax

[Assertion]
zend.assertions=-1

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.save_comments=1
